server:
  servlet:
    context-path: /bibliotech
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotech
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      book: topic-bibliotech-books
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: bibliotech-group
      listener:
        missing-topics-fatal: false
external:
  api:
    isbn:
      url: XXXXXXXXXX
      key: XXXXXX
    openLibrary:
      login: ${OPEN_LIBRARY_LOGIN}
      key: ${OPEN_LIBRARY_KEY}
      login-api:
        url: https://openlibrary.org/account/login
      covers-api:
        url: https://covers.openlibrary.org/b
      books-api:
        url: https://openlibrary.org/api/volumes/brief/
    openAI:
      key: ${OPENAI_API_KEY}
      url: https://api.openai.com/v1/chat/completions
      active: false