server:
  servlet:
    context-path: /biblioto
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioto
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
external:
  api:
    isbn:
      url: XXXXXXXXXX
      key: XXXXXX
    openLibrary:
      login: ${OPENLIBRARY_LOGIN}
      key: ${OPENLIBRARY_KEY}
      login-api:
        url: https://openlibrary.org/account/login
      covers-api:
        url: https://covers.openlibrary.org/b
      books-api:
        url: https://openlibrary.org/api/volumes/brief/
    openAI:
      key: ${OPENAI_API_KEY}
      url: https://api.openai.com/v1/chat/completions
